import torch
import torch.nn as nn
import torch.nn.functional as F


class TargetFC(nn.Module):
    """
    Fully connected layer whose parameters are generated by HyperNet.
    This module is used by TargetNet for image-adaptive quality regression.
    """
    def __init__(self, weight, bias):
        super(TargetFC, self).__init__()
        self.weight = weight
        self.bias = bias

    def forward(self, x):
        # x: [B, in_features, 1, 1] or [B, in_features]
        if x.dim() == 4:
            x = x.view(x.size(0), -1)

        # weight: [B, out_features, in_features, 1, 1]
        w = self.weight.view(self.weight.size(0), self.weight.size(1), self.weight.size(2))

        # batch matrix multiplication: [B, 1, in] x [B, in, out]
        out = torch.bmm(x.unsqueeze(1), w.transpose(1, 2)).squeeze(1)
        out = out + self.bias
        return out


class TargetNet(nn.Module):
    """
    Lightweight target network used by MS-WaveViT.

    The weights and biases of this network are generated dynamically by
    the HyperNet branch in wave_models/wavehypernet.py.
    """
    def __init__(self, paras):
        super(TargetNet, self).__init__()

        self.fc1 = TargetFC(paras['target_fc1w'], paras['target_fc1b'])
        self.fc2 = TargetFC(paras['target_fc2w'], paras['target_fc2b'])
        self.fc3 = TargetFC(paras['target_fc3w'], paras['target_fc3b'])

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)

        x = self.fc2(x)
        x = F.relu(x)

        x = self.fc3(x)
        return x
